# -*- coding: utf-8 -*-
"""(1) 수시 도로유형별 교통량 조회

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aNU7TfkyzxeLp_pWtGrMfc6FQacI6F_

## 오픈 API crawlering

### 공공데이터 호출하고 데이터 뽑기

### 수시 도로유형별 교통량 조회

https://www.data.go.kr/iim/api/selectAPIAcountView.do
"""

! pip install xmltodict

"""dtype = 1일때 count = 24240 <br/>
dtype = 2일때 count = 50592 <br/>
dtype = 3일때 count = 58224 <br/>
dtype = 4일때 count =<br/>
dtype = 5일때 count = 17472 <br/>
"""

import pandas as pd
from pandas.io.json import json_normalize
import requests
import pprint
import json

# url 입력 (https 말고 http로 수정)

#count=24240
#pageNo=49
#numOfRows=500

#count=50592
#pageNo=102
#numOfRows=500

#count=58224 ~ 할차례
#pageNo=117
#numOfRows=500

#

#count=17472
#pageNo=35
#numOfRows=500


dataframe = pd.DataFrame(columns=['spot_id', 'direction', 'hour', 'vehicle_type1', 'vehicle_type2',
       'vehicle_type3', 'vehicle_type4', 'vehicle_type5', 'vehicle_type6',
       'vehicle_type7', 'vehicle_type8', 'vehicle_type9', 'vehicle_type10',
       'vehicle_type11', 'vehicle_type12', 'total_count'])

# list = [0,1,2,3,4,5] 

for i in range(35):
  url = 'http://apis.data.go.kr/1613000/KICTopenAPI/spothcv?serviceKey=^.^&year=2020&dtype=5&output=json&pageNo={}'.format(i) + '&numOfRows=500&type=json'

  # url 불러오기
  response = requests.get(url) # 신뢰할 수 없는 SSL 인증서로 인해 발생, verify=False 구문 추가

  # 데이터 값 출력해보기
  contents = response.text

  # 문자열을 json으로 변경
  json_ob = json.loads(contents) ## dtype 2에서 여기서 에러뜸
                                 ## 에러가 날때도 있고 안날때도 있음, 서버 불안정 문제거나
                                 ## 트래픽 한도 초과일 가능성도 있음

  # 필요한 부분만 추출
  body = json_ob['traffic']

  # 데이터프레임으로 변환
  dataframe_i = json_normalize(body)

  # 데이터프레임 append
  dataframe = dataframe.append(dataframe_i)
  dataframe = dataframe.reset_index(drop=True)

dataframe

dataframe.to_csv('dataframe2020(5).csv',index=False)

dataframe1 = pd.read_csv('dataframe2020(1).csv')
dataframe2 = pd.read_csv('dataframe2020(2).csv')
dataframe3 = pd.read_csv('dataframe2020(3).csv')
dataframe5 = pd.read_csv('dataframe2020(5).csv')

"""#### 칼럼 추가"""

dataframe1['dtype'] = 1
dataframe2['dtype'] = 2
dataframe3['dtype'] = 3
dataframe5['dtype'] = 5

dataframe2020 = pd.concat([dataframe1,dataframe2,dataframe3,dataframe5])
dataframe2020 = dataframe2020.reset_index(drop=True)
dataframe2020 # 150528 * 17

dataframe2020.to_csv('dataframe2020.csv',index=False)

"""## 💥"""