# -*- coding: utf-8 -*-
"""(2) 상시 차종별 교통량 조회

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nHA4xmdZGfxUW0Ej4k1sqMexandC3nMc

## 상시 차종별 교통량 조회

상시 수집된 교통 데이터 중 연도, 도로 종류를 통해 지정한 <br/>
연도에 선택된 도로(고속도로, 일반도로 등)를 통행한 차량 종류별 통행량을 <br/> 조회하는 기능

https://www.data.go.kr/iim/api/selectAPIAcountView.do
"""

! pip install xmltodict

import json

def parse_re(input_re: str):
    try:
        return_dict = json.loads(input_re)
    except json.decoder.JSONDecodeError:
        return_dict = dict()
    finally:
        return return_dict

import pandas as pd
from pandas.io.json import json_normalize
import requests
import pprint
import json

dataframe = pd.DataFrame(columns=['spot_id', 'month', 'day', 'direction', 'vehicle_type1', 'vehicle_type2',
       'vehicle_type3', 'vehicle_type4', 'vehicle_type5', 'vehicle_type6',
       'vehicle_type7', 'vehicle_type8', 'vehicle_type9', 'vehicle_type10',
       'vehicle_type11', 'vehicle_type12', 'total_count'])

i = 0

url = 'http://apis.data.go.kr/1613000/KICTopenAPI/vt?serviceKey=^.^&year=2020&dtype=2&output=json&pageNo={}'.format(i) + '&month=12&numOfRows=28770&type=json'
# url 불러오기
response = requests.get(url)

# 데이터 값 출력해보기
contents = response.text

# 문자열을 json으로 변경
#json_ob = json.loads(contents) ## dtype 2에서 여기서 에러뜸
json_ob = parse_re(contents)

# 필요한 부분만 추출
body = json_ob['traffic']

# 데이터프레임으로 변환
dataframe_i = json_normalize(body)

# 데이터프레임 append
dataframe = dataframe.append(dataframe_i)
dataframe = dataframe.reset_index(drop=True)

dataframe

dataframe.to_csv('totalcount_vehicle2020_dtype2(12).csv',index=False)

dataframe1 = pd.read_csv('totalcount_vehicle2020_dtype2.csv')
dataframe2 = pd.read_csv('totalcount_vehicle2020_dtype2(2).csv')
dataframe3 = pd.read_csv('totalcount_vehicle2020_dtype2(3).csv')
dataframe4 = pd.read_csv('totalcount_vehicle2020_dtype2(4).csv')
dataframe5 = pd.read_csv('totalcount_vehicle2020_dtype2(5).csv')
dataframe6 = pd.read_csv('totalcount_vehicle2020_dtype2(6).csv')
dataframe7 = pd.read_csv('totalcount_vehicle2020_dtype2(7).csv')
dataframe8 = pd.read_csv('totalcount_vehicle2020_dtype2(8).csv')
dataframe9 = pd.read_csv('totalcount_vehicle2020_dtype2(9).csv')
dataframe10 = pd.read_csv('totalcount_vehicle2020_dtype2(10).csv')
dataframe11 = pd.read_csv('totalcount_vehicle2020_dtype2(11).csv')
dataframe12 = pd.read_csv('totalcount_vehicle2020_dtype2(12).csv')

totalcount_vehicle2020_dtype2_total = pd.concat([dataframe1,dataframe2,dataframe3,dataframe5,
                                    dataframe6,dataframe7,dataframe8,dataframe9,dataframe10,dataframe11,dataframe12])
totalcount_vehicle2020_dtype2_total = totalcount_vehicle2020_dtype2_total.reset_index(drop=True)
totalcount_vehicle2020_dtype2_total # 312578 * 17

"""#### 칼럼 추가"""

totalcount_vehicle2020_dtype2_total['dtype'] = 2
totalcount_vehicle2020_dtype2_total

totalcount_vehicle2020_dtype2_total.to_csv('totalcount_vehicle2020_dtype2_total.csv',index=False)
