# -*- coding: utf-8 -*-
"""(4) 교통량 측정 지점 조회

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ddlwFPguVZdGbFUbrvqBG0XWAcnVvYhS

## 교통량 측정 지점 조회

연도, 도로 종류를 통해 지정한 연도에 선택된 도로(고속도로, 일반도로 등)의 <br/>교통량 측정 지점에 대한 정보를 조회하는 기능

https://www.data.go.kr/iim/api/selectAPIAcountView.do
"""

! pip install xmltodict

import json

def parse_re(input_re: str):
    try:
        return_dict = json.loads(input_re)
    except json.decoder.JSONDecodeError:
        return_dict = dict()
    finally:
        return return_dict

import pandas as pd
from pandas.io.json import json_normalize
import requests
import pprint
import json

dataframe = pd.DataFrame(columns=['dolevel','year','spot','gugan_no','docode','stname',
                                  'midname','endname','hosun','laneup','lanedn','city','section','country','locate',
                                  'length','remark','id5','xcode','ycode'])

i = 0

url = 'http://apis.data.go.kr/1613000/KICTopenAPI/spotlist?serviceKey=^.^&year=2020&dtype=5&output=json&pageNo={}'.format(i) + '&numOfRows=364&type=json'
# url 불러오기
response = requests.get(url) 

# 데이터 값 출력해보기
contents = response.text

# 문자열을 json으로 변경
#json_ob = json.loads(contents) 
json_ob = parse_re(contents)

# 필요한 부분만 추출
body = json_ob['spot']

# 데이터프레임으로 변환
dataframe_i = json_normalize(body)

# 데이터프레임 append
dataframe = dataframe.append(dataframe_i)
dataframe = dataframe.reset_index(drop=True)

dataframe

dataframe['dtype'] = 5
dataframe

dataframe.to_csv('loadnamedtype5.csv',index=False)

dataframe1 = pd.read_csv('loadnamedtype1.csv')
dataframe2 = pd.read_csv('loadnamedtype2.csv')
dataframe3 = pd.read_csv('loadnamedtype3.csv')
dataframe5 = pd.read_csv('loadnamedtype5.csv')

loadname = pd.concat([dataframe1,dataframe2,dataframe3,dataframe5])
loadname = loadname.reset_index(drop=True)
loadname # 3793 * 21

loadname.to_csv('loadname.csv',index=False)