# -*- coding: utf-8 -*-
"""(5) 측정 장치 목록 조회

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12hj7mf0SXI-cZZa-MbmChM-LeEMgfwcL

## 측정 장치 목록 조회

전체 교통량 측정 장치 목록을 확인하는 기능

https://www.data.go.kr/iim/api/selectAPIAcountView.do
"""

! pip install xmltodict

import json

def parse_re(input_re: str):
    try:
        return_dict = json.loads(input_re)
    except json.decoder.JSONDecodeError:
        return_dict = dict()
    finally:
        return return_dict

import pandas as pd
from pandas.io.json import json_normalize
import requests
import pprint
import json

dataframe = pd.DataFrame(columns=['id', 'type', 'lat', 'lng', 'address', 'zone'])

i = 0 # equipment_id

url = 'http://apis.data.go.kr/1613000/KICTopenAPI/eqplist?serviceKey=^.^&numOfRows=5000&output=json&type=json'
# url 불러오기
response = requests.get(url) 

# 데이터 값 출력해보기
contents = response.text

# 문자열을 json으로 변경
#json_ob = json.loads(contents) 
json_ob = parse_re(contents)

# 필요한 부분만 추출
body = json_ob['equipment']

# 데이터프레임으로 변환
dataframe_i = json_normalize(body)

# 데이터프레임 append
dataframe = dataframe.append(dataframe_i)
dataframe = dataframe.reset_index(drop=True)

"""<깃허브 업로드용_인증키삭제>"""

dataframe

dataframe.to_csv('equipmentlist.csv',index=False)